version: '3.8'

services:
  web:
    build:
      context: .
    volumes:
      - static:/static
    environment:
      - MODE=web
    depends_on:
      - redis
      - db
    env_file:
      - .env.sample
  db:
    image: mysql:latest
    container_name: 'mydb'
    command: --init-file /docker-entrypoint-initdb.d/init-script.sql

    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      MYSQL_USER: abantether
      MYSQL_PASSWORD: abanpass
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: abantether

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data


  celery:
    build: .
    env_file:
      - .env.sample
    environment:
      - MODE=worker
    depends_on:
      - redis

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - web
    restart: "on-failure"

volumes:
  static: